### ISSUE TITLE
Adjusting Robot Height

### ISSUE THREAD

**Issue by YandongJi** [chvmp/champ_teleop#1]
Hi, if I need to adjust the robots' height in teleop.py, what parameters do I need to change? I tuned nominal_height but it's not working. Thx

**Comment by grassjelly** [comment]
Hi, 

You can change the robot height in this line. https://github.com/chvmp/champ_teleop/blob/master/champ_teleop.py#L109
The z value sent from the teleop is the required translation of the floating base from it's current height (nominal height). Current implementation only translates in the minus z axis https://github.com/chvmp/champ_teleop/blob/master/champ_teleop.py#L108 .

**Comment by YandongJi** [comment]
thank you for helping! I'm trying to send pose command directly to robots and however I didn't find a topic named body_pose/raw. The command I used was "rostopic list"

**Comment by grassjelly** [comment]
If you want to control the robot's pose directly, you can use 'geometry_msgs/Pose' and publish to body_pose topic. 
 You can take a look at these lines https://github.com/chvmp/champ_teleop/blob/master/champ_teleop.py#L113-L122.

**Comment by grassjelly** [comment]
Hey @YandongJi just wondering are you from Dogotix?

**Comment by YandongJi** [comment]
hmm, no, am senior student from Nankai University, China.

**Comment by yuetaoWei** [comment]
excuse me@YandongJi ,I am learning how to use the motor of Dogotix mechanical dog, do you have the specific information, is it convenient to exchange,my email is y18925691605@163.com Even though I know this conversation has been over for a long time

**Comment by YandongJi** [comment]
Hi Yuetao, I don't have its information yet.

**Comment by yuetaoWei** [comment]
any way thank you to reply so quick,i decide to chang to use unitree motor
